# Generated by Django 5.1.3 on 2024-11-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0002_review_rating_score_watchlist_delete_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating_score',
            new_name='review_score',
        ),
    ]
