# Generated by Django 5.1.3 on 2024-11-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0003_rename_rating_score_review_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
