# Generated by Django 5.1.3 on 2024-11-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0004_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
