# Generated by Django 5.1.3 on 2024-11-20 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review', '0005_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movie_review.reviewer'),
            preserve_default=False,
        ),
    ]
