# Generated by Django 5.1.1 on 2024-10-01 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('city', models.TextField()),
                ('emailAddr', models.TextField()),
                ('ProfileImg', models.URLField(blank=True)),
            ],
        ),
    ]
